//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 12.09.2016 09:35:55
namespace HumbleGuns
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class GUI
            {
                
                /// <summary> Path to Content/Assets/GUI/rendertarget.jpg </summary>
                public const string rendertarget_jpg = "Content/Assets/GUI/rendertarget.jpg";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/DefaultTexture.png </summary>
                public const string DefaultTexture_png = "Content/Assets/Textures/DefaultTexture.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
