//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 16.09.2016 18:18:50
namespace HumbleGuns
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class GUI
            {
                
                /// <summary> Path to Content/Assets/GUI/rendertarget.jpg </summary>
                public const string rendertarget_jpg = "Content/Assets/GUI/rendertarget.jpg";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/DefaultTexture.png </summary>
                public const string DefaultTexture_png = "Content/Assets/Textures/DefaultTexture.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
